//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SebContactsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_detail
    {
        public int cd_id { get; set; }
        public string cd_ow_account { get; set; }
        public string cd_import_account { get; set; }
        public string cd_alternative_account { get; set; }
        public string cd_statement_name { get; set; }
        public string cd_statement_address1 { get; set; }
        public string cd_statement_address2 { get; set; }
        public string cd_statement_address3 { get; set; }
        public string cd_statement_town { get; set; }
        public string cd_statement_county { get; set; }
        public string cd_statement_country { get; set; }
        public string cd_statement_postcode { get; set; }
        public string cd_statement_email { get; set; }
        public string cd_statement_website { get; set; }
        public string cd_statement_telephone { get; set; }
        public string cd_statement_fax { get; set; }
        public string cd_invoice_name { get; set; }
        public string cd_invoice_address1 { get; set; }
        public string cd_invoice_address2 { get; set; }
        public string cd_invoice_address3 { get; set; }
        public string cd_invoice_town { get; set; }
        public string cd_invoice_county { get; set; }
        public string cd_invoice_country { get; set; }
        public string cd_invoice_postcode { get; set; }
        public string cd_invoice_email { get; set; }
        public string cd_invoice_website { get; set; }
        public string cd_invoice_telephone { get; set; }
        public string cd_invoice_fax { get; set; }
        public string cd_vat_number { get; set; }
        public string cd_statment_country_code { get; set; }
        public string cd_invoice_country_code { get; set; }
        public bool cd_account_customer { get; set; }
        public Nullable<int> cd_cde_id { get; set; }
        public string cd_company_registration_number { get; set; }
        public Nullable<int> cd_gdprr_id { get; set; }
        public string cd_eori_no { get; set; }
        public string cd_ioss_no { get; set; }
    }
}
